# Generated by Django 4.1.7 on 2023-04-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='CoverLetters/'),
        ),
        migrations.AddField(
            model_name='users',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='Resumes/'),
        ),
    ]
