# Generated by Django 4.1.7 on 2023-04-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_users_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_postings',
            name='is_fulltime',
            field=models.BooleanField(default=True),
        ),
    ]
