# Generated by Django 4.1.7 on 2023-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_job_postings_is_fulltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_postings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companyLogos/'),
        ),
    ]
