# Generated by Django 4.1.7 on 2023-04-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_job_postings_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_postings',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
