# Generated by Django 4.1.7 on 2023-04-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_job_postings_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_postings',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categories'),
        ),
    ]
